name: pages build and deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy MkDocs site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-terminal pymdown-extensions

      - name: Build site
        run: mkdocs build --clean

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
          publish_branch: gh-pages
          # Uses the GITHUB_TOKEN automatically; no secrets required
